# -*- coding: utf-8 -*-
"""s1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRVfJsDRNXtd8d3ZhPD7luSWHXSWqWoC

## <font face="gotham" color="blue"> **COBB-DOUGLAS**</font>

`Luis Chávez`

2015

![texto del vínculo](https://cdn-icons-png.freepik.com/256/18637/18637672.png?ga=GA1.1.939083639.1744493239&semt=ais_hybrid)

### <font face="gotham" color="blue"> **Forma Básica**</font>
"""

import numpy as np
import matplotlib.pyplot as plt

def cobb_douglas(K, L, alpha=0.3, A=1):
  """
  Cobb-Douglas production function.
  Args:
    K: Capital input.
    L: Labor input.
    alpha: Capital share parameter (0 < alpha < 1).
    A: Total factor productivity.
  Returns:
    The output produced.
  """
  return A * (K**alpha) * (L**(1 - alpha))

K_vals = np.linspace(1, 10, 100)  # Range capital
L_vals = np.linspace(1, 10, 100)  # Range labor
K, L = np.meshgrid(K_vals, L_vals)
Y = cobb_douglas(K, L)

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(K, L, Y, cmap='viridis')

ax.set_xlabel("K")
ax.set_ylabel("L")
ax.set_zlabel("Y")
ax.set_title("Cobb-Douglas Function")
plt.show()

# Ejemplo 1:
capital = 5
labor = 7
output = cobb_douglas(capital, labor)
print(f"Output with capital {capital} and labor {labor}: {output}")

"""### <font face="gotham" color="blue"> **Forma interactiva parametrizada**</font>"""

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, fixed

def cobb_douglas_interactive(K, L, alpha=0.3, A=1):
  """
  Interactive Cobb-Douglas production function.
  """
  Y = cobb_douglas(K, L, alpha, A)
  print(f"Output with capital {K} and labor {L}: {Y}")

  fig = plt.figure(figsize=(10, 8))
  ax = fig.add_subplot(111, projection='3d')
  K_vals = np.linspace(1, 10, 100)
  L_vals = np.linspace(1, 10, 100)
  K_grid, L_grid = np.meshgrid(K_vals, L_vals)
  Y_grid = cobb_douglas(K_grid, L_grid, alpha, A)
  ax.plot_surface(K_grid, L_grid, Y_grid, cmap='viridis')

  ax.set_xlabel("K")
  ax.set_ylabel("L")
  ax.set_zlabel("Y")
  ax.set_title("Cobb-Douglas Function")
  plt.show()

interact(cobb_douglas_interactive, K=(1, 10, 0.1), L=(1, 10, 0.1), alpha=(0.1, 0.9, 0.1), A=(0.5, 2, 0.1));

"""### <font face="gotham" color="blue"> **Forma interactiva libre**</font>"""

import plotly.graph_objects as go
import numpy as np

def cobb_douglas(K, L, A, alpha, beta):
    return A * (K**alpha) * (L**beta)

k_range = np.linspace(0.1, 5, 50)
l_range = np.linspace(0.1, 5, 50)
K, L = np.meshgrid(k_range, l_range)
A = 1
alpha = 0.3
beta = 0.7

Z = cobb_douglas(K, L, A, alpha, beta)
fig = go.Figure(data=[go.Surface(z=Z, x=K, y=L)])
fig.update_layout(
    title='Función de Producción Cobb-Douglas', width=800, height=600,
    scene=dict(
        xaxis_title='K',
        yaxis_title='L',
        zaxis_title='Y',
        camera=dict(
            eye=dict(x=1.25, y=1.25, z=1.25) # Posición inicial de la cámara
        )
    )
)
fig.show()